apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |-
    [server]
    root_url = http://localhost:3000
    
    [auth.anonymous]
    enabled = true
    org_role = Admin
    
    [security]
    allow_embedding = true
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Admin
