apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo-app
  namespace: monitoring
  labels:
    app: monitoring-demo-app
spec:
  selector:
    app: monitoring-demo-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
