apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-demo-app
  namespace: monitoring
  labels:
    app: monitoring-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-demo-app
  template:
    metadata:
      labels:
        app: monitoring-demo-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: monitoring-demo-app
        image: ${YOUR_DOCKERHUB_USERNAME}/monitoring-demo-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
